# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 17:39
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20171003_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(verbose_name='Issue Description')),
                ('is_closed', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[('3', 'AWAITING_QA'), ('1', 'IN_PROGRESS'), ('0', 'NEW'), ('2', 'ON_HOLD'), ('4', 'QA_VERIFIED')], default=0)),
                ('tracker', models.IntegerField(choices=[('0', 'BUG'), ('1', 'FEATURE'), ('2', 'SUPPORT')], default=0)),
                ('priority', models.IntegerField(choices=[('2', 'HIGH'), ('0', 'LOW'), ('1', 'NORMAL'), ('3', 'URGENT')], default=0)),
                ('due_date', models.DateField(null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(null=True)),
                ('documents', models.ManyToManyField(to='pms.Document')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.Project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='watchers',
            field=models.ManyToManyField(related_name='watchers', to='core.Profile'),
        ),
    ]
