# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 12:40
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.IntegerField(choices=[(0, 'CREATE'), (3, 'DELETE'), (1, 'RETRIEVE'), (2, 'UPDATE')], default=1)),
                ('operational_text', models.CharField(blank=True, max_length=256, null=True)),
                ('model_name', models.CharField(blank=True, max_length=64, null=True)),
                ('app_level', models.CharField(blank=True, max_length=32, null=True)),
                ('reference_id', models.IntegerField(null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(verbose_name='Issue Description')),
                ('progress', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(6, 'ARCHIVE'), (3, 'AWAITING_QA'), (5, 'CLOSE'), (1, 'IN_PROGRESS'), (0, 'NEW'), (2, 'ON_HOLD'), (4, 'QA_VERIFIED')], default=0)),
                ('tracker', models.IntegerField(choices=[(0, 'BUG'), (1, 'FEATURE'), (2, 'SUPPORT')], default=0)),
                ('priority', models.IntegerField(choices=[(2, 'HIGH'), (0, 'LOW'), (1, 'NORMAL'), (3, 'URGENT')], default=0)),
                ('due_date', models.DateTimeField(null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='core.Profile')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='IssueHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_progress', models.IntegerField(default=0)),
                ('old_description', models.TextField(blank=True, null=True, verbose_name='Old Description')),
                ('new_description', models.TextField(blank=True, null=True, verbose_name='New Description')),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_by', to='core.Profile')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.Issue')),
                ('new_assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_assignee', to='core.Profile')),
                ('old_assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_assignee', to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(null=True)),
                ('documents', models.ManyToManyField(to='pms.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=360)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.Project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='watchers',
            field=models.ManyToManyField(related_name='watchers', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pms.Issue'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(to='pms.Reply'),
        ),
    ]
