# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuehistory',
            old_name='current_progress',
            new_name='new_progress',
        ),
        migrations.AddField(
            model_name='issuehistory',
            name='old_progress',
            field=models.IntegerField(default=0),
        ),
    ]
