# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_auto_20171015_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='is_closed',
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(6, 'ARCHIVE'), (3, 'AWAITING_QA'), (5, 'CLOSE'), (1, 'IN_PROGRESS'), (0, 'NEW'), (2, 'ON_HOLD'), (4, 'QA_VERIFIED')], default=0),
        ),
    ]
