# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_auto_20171121_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='comment',
        ),
        migrations.AddField(
            model_name='conversation',
            name='comment',
            field=models.ManyToManyField(to='pms.Comment'),
        ),
    ]
