# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pms', '0003_auto_20171016_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_description', models.TextField(blank=True, null=True, verbose_name='Old Description')),
                ('new_description', models.TextField(blank=True, null=True, verbose_name='New Description')),
                ('comment', models.CharField(blank=True, max_length=256, null=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_by', to='core.Profile')),
                ('new_assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_assignee', to='core.Profile')),
                ('old_assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_assignee', to='core.Profile')),
            ],
        ),
    ]
