# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_auto_20171006_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
