# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_auto_20171122_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='comment',
            new_name='comments',
        ),
    ]
