# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_issuehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuehistory',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.Issue'),
            preserve_default=False,
        ),
    ]
