# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 03:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import pms.helpers.enums


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20171003_1611'),
        ('pms', '0004_auto_20171006_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.IntegerField(choices=[(0, 'CREATE'), (3, 'DELETE'), (1, 'RETRIEVE'), (2, 'UPDATE')],
                                               default=pms.helpers.enums.ActionEnum.RETRIEVE.value)),
                ('operational_text', models.CharField(blank=True, max_length=256, null=True)),
                ('model_name', models.CharField(blank=True, max_length=64, null=True)),
                ('app_level', models.CharField(blank=True, max_length=32, null=True)),
                ('reference_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.Comment')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=360)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(to='pms.Reply'),
        ),
    ]
