# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pms', '0005_auto_20171122_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to='core.Profile'),
        ),
    ]
