# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_issuehistory_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuehistory',
            name='current_progress',
            field=models.IntegerField(default=0),
        ),
    ]
