# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_auto_20171015_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='user',
            new_name='profile',
        ),
    ]
