# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_auto_20171015_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.IntegerField(choices=[(0, 'CREATE'), (3, 'DELETE'), (1, 'RETRIEVE'), (2, 'UPDATE')], default=1),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='reference_id',
            field=models.IntegerField(null=True),
        ),
    ]
